### PR TITLE
chore: bump version to v0.4.0

### PR DESCRIPTION
**Pull request by waynexia**
# Which issue does this PR close?

Closes #

# Rationale for this change
 

# What changes are included in this PR?

# Are there any user-facing changes?

#36 introduces a breaking change:
>the `Database` trait adds a new parameter `QueryContext` which is a string-to-string key value map.

# How does this change test

### CODE REVIEW

**Review by jiacai2050 — APPROVED** [review]
LGTM

**Comment by jiacai2050** [comment]
I will push v0.4.0 tag to automatically release on crates..

**Comment by jiacai2050** [comment]
https://github.com/CeresDB/sqlness/actions/runs/4291226934

**Comment by waynexia** [comment]
Thanks, just got back from a meeting...

**Pull request merged**
